module.exports = {
    language: {
        name: 'English'
    },
    user: {
        login:'login',
        register:'register',
        loginUsername:'please input email or phone',
		enterPassword:'enter your PIN',
		remenberP:'remember the password',
		forgetP:'forget the password',
		readAgree:'I have read it and fully agree to accept it',
		userAgreement:'user agreement',
		riskwarning:'Risk warning',
		download:'Download',
		yourname:'Please enter your user name',
		yourpassword:'Please enter your login password',
		yourpasswordtwo:'Please enter your login password again',
		transactionpassword:'Please enter your transaction password',
		transactionpasswordtwo:'Please enter your transaction password again',
		Invitationcode:'Please enter your invitation code',
		verification:'Please enter the verification code',
		getcode:'get code',
		gain:'gain',
		Pleasecomplete:'Please complete',
		donmatch:'The two passwords dont match',
		transactionmatch:'The passwords for the two transactions do not match',
		readAgreement:'Please read the User Agreement',
		Islanding:'Is landing',
		loginfailure:'login failure',
		loginP:'login password',
		transactionp:'transaction pin',
		alter:' Alter',
		oldP:'Nld password',
		news:'New',
		confirmP:'confirm password',
		authcode:'auth code',
		pleaseInput:'please input ',
		pleaseInputTwo:'Please input again',
		Confirm:'Confirm',
		Interchange:' Interchange  ',
		credited:'account to be credited',
		chamberlain:'chamberlain',
		Transfer:'Transfer quantity',
		all:'All',
		remaining:'sum',
    },
	index:{
		homepage:'Home',
		store:'Store',
		quantization:'quantify',
		find:'find',
		my:'My',
		more:'more',
		Cryptocurrency:'CryptocurrencyName',
		Latestprice:'LatestPrice',
		Updown:'UpAndDown',
		Registered:'Registered',
		Recharge:'Recharge',
		Mention:'Withdrawal',
		record:' record',
		Interchange:'Interchange Center',
		community:'My community',
		Agent:'Agent center',
		BindWallet:'Bind Wallet',
		Security:'Security Center',
		service:'Contact customer service',
		Quantitative:'quantify ecological platform',
		assets:'Assets',
		partnership:' partner',
		recharges:'One-time recharge',
		equity:'And obtain the qualifications of CR partners and enjoy the relevant rights and interests of CR partners',
		BuyNow:'Buy now',
		hint:'prompt',
		supported:"Do you have a clear understanding of the agency rules. If there are no doubts or objections, click '确定' to purchase successfully. Once purchased, no return or exchange is supported."
	},
	notecase:{
		system:'Intelligent quantify system',
		regulate:'Regulate',
		spotquantify:' spotQuantify',
		swapquantify:'swapQuantify',
		follow:'strategyFollow',
		quantify:'Quantify Revenue Ranking',
		today:'Today',
		week:'ThisWeek',
		month:'ThisMonth',
		income:'Income',
		address:'Withdrawal address',
		select:'Select this address',
		compile:'edit',
		deletes:'delete',
		add:'Add to',
		that:'This one',
		name:'Name',
		currency:'Currency',
		wallet:'Wallet address',
		your:'Your',
		withdrawal:'Please upload the QR code for withdrawal',
		defaults:'default',
		uploading:'Uploading',
		uploadings:'Uploaded successfully',
		uploadingload:'upload failed',
		Chinese:'Cant input Chinese'
	},
	store:{
		buy:' Buy',
		Shopping:'ShoppingVoucher',
		Performance:'Performance',
		Product:'ProductArea',
		other:'other',
		spot:'spot',
		swap:'swap',
		intelligent:'Intelligent',
		robot:'Robot',
		Billing:'Billing Edition',
		profession:'Profession',
		Term:'Term Edition',
		Strategy:'Policy',
		following:'Follow',
		duration:'Duration',
		price:'Price',
		day:'Day',
		remarks:'Remarks',
		Billingremarks:'The first activation must be 200USDT to purchase for 360 days, and after the successful purchase, the USDT handling fee balance is not less than 10USDT to activate all products and open transactions.',
		
		Enter:'Enter',
		XLMT:'XL MT',
		channel:'Please select USDT-TRC20 channel',
		Sungha:'Point card version',
		Remaining:'Remaining',
		pointcard:' point card',
		dot:'dot',
		logon:'log on',
		beactivated:'To be activated',
		version:'version',
		unpurchased:'Not purchased'
	},
	callcenter:{
		unique:'Your exclusive',
		WeChat:'WeChat',
		customer:'We will provide you with customer service',
		employ:'employ',
		Identify:'Identify and add customer service',
		service:'Service',
		guide:'Guide',
		notice:'Notice',
		system:'System',
		sprog:'Sprog',
		amount:'amount',
		Entries:'Entries',
		duration:'effectiveDuration',
		buying:'time buying',
		payment:'payment amount',
		completion:'completion of payment',
		inactive:'inactive',
		activated:'activated',
		activation:'activationTime',
	},
	community:{
		community:'Community',
		remaining:'timeRemaining',
		Renew:'Renew',
		List:'List',
		search:'search',
		ranking:'integratedRanking',
		type:'type',
		running:'running',
		trading:'in trading',
		Stopped:'Stopped:',
		population:'Number of followers',
		accumulative:'accumulative',
		win:'win rate',
		transactions:'total transactions',
		revenue:'revenue',
		rate:'rate',
		activate:'activate',
		Feed:'Data Feed',
		Huobi:'Huobi',
		sustainability:'sustainability',
		total:'Total',
		money:'money',
		set:'set',
		available:'No more data available',
		loaded:'All data has been loaded',
		load:'The drop-down load',
	},
	spot:{
		success:'Refresh the success',
		Station:' Global Station',
		instructions:'instructions',
		monitoring:'monitoring',
		configure:'configure',
		Valuation:'Valuation currency',
		pair:'Add currency pair',
	    setup:'One-click setup application',
		monitoringtwo:'real time monitoring',
		deals:'Number of deals',
		profits:'Complete the profits',
        result:'computational results',
		Record:'Transaction Record',
		Delete:'deletion',
		set:'Set policies',
		open:'Open',
		renew:'resumed',
		stop:'stop trading',
		noopen:'not open',
		status:'status',
		Under:'Under monitoring',
		Check:'Stop profit and then stop',
		error:' error',
		Positioning:'Positions',
		capital :'undercapitalized',
		singular:'Builds a singular',
		odd:'odd',
		number:'Position the number',
		average:'Position the average',
		storehouse:'The average tail storehouse',
		receipt:'Flat warehouse receipt number',
		profit:'take profits',
		andloss:'Floating P/L',
		proceeds:'Settlement income',
		stoppage:'Temporary stop',
		album:'Save the QR code to the album',
		site:'Filling currency address',
		copy:'copy',
		account:'After successful recharge, please copy the transaction hash ID, click confirm in the input box, and the system will arrive after authentication',
		hash:'Enter the hash value',
		Cautions:'Cautions',
		please:'Please do not recharge any non usdt-trc20 assets to the above address, otherwise the assets will not be retrieved. After you successfully recharge to the above address, you need to copy the transaction hash ID, and then the transaction will arrive after network confirmation. Please make sure the computer and browser are safe to prevent information from being tampered or leaked',
		wallet:'The wallet address',
		successtwo:'Copy success',
		replication:'The browser does not support automatic replication',
		successfully:'save successfully',
		jurisdiction:'Save failure: Transcoding failure or no access to album',
		code:'My invitation QR code',
		Invitation:'My invitation code',
		link:'My invitation link',
		poster:'Generate invitation posters',
		details:'Bonus details',
		Straight:'Directly invited users',
		Username:'Community user',
		position:'Rank',
		earnings:'Profit today',
		Earnings:'Quantify total profit',
		Bonus:'BonusIncomeToday',
		returns:'Total bonus income',
		 invitation:'My invitation details',
		 Rtime:'registration time',
		 rebate:'Rebate',
		 loadM:'Load more',
		 TradingC:'Transaction consumption',
		 budget:'principal budget',
		start:'one-click start',
		cease:'one-click stop',
		install:'budget setting',
		close:'one-click close',
		reset:'reset strategy',
		amounts:'transaction amount'
	},
	matter:{
		matter:' Intelligent trading considerations',
		bound:'The API generated by the user within the exchange is not IP bound',
		deal:'Before smart trading can be done, there must be capital in the exchange before the system can execute the trade',
		promptly:'After the smart transaction is started, if there is manual intervention, the system will immediately stop the transaction'
	}
}