module.exports = {
    language: {
        name: '한글'
    },
    user: {
        login:'등록 하 다',
        register:'등록 하 다',
        loginUsername:'핸드폰 번호 나 메 일주 소 를 입력 하 세 요',
		enterPassword:'비밀 번 호 를 입력 하 세 요',
		remenberP:'비밀 번 호 를 기억 하 다',
		forgetP:'비밀 번 호 를 잊어버리다',
		readAgree:'나 는 이미 읽 고 완전히 받 아 들 였 다',
		userAgreement:'사용자 프로 토 콜',
		riskwarning:'위험 제시 서',
		download:'다운로드 하 다',
		yourname:'당신 의 아 이 디 를 입력 하 세 요',
		yourpassword:'로그 인 비밀 번 호 를 입력 하 세 요',
		yourpasswordtwo:'로그인 비밀번호를 다시 입력하십시오',
		transactionpassword:'거래 비밀번호를 입력하십시오',
		transactionpasswordtwo:'거래 비밀번호를 다시 입력하십시오',
		Invitationcode:'초대장 번호를 입력하십시오',
		verification:'인증번호를 입력하십시오',
		getcode:'인증 코드 가져오기',
		gain:'경쾌하다',
		Pleasecomplete:'완전히 채워주세요',
		donmatch:'비밀번호가 일치하지 않습니다',
		transactionmatch:'비밀번호가 일치하지 않습니다',
		readAgreement:'사용자 프로토콜을 읽으십시오',
		Islanding:'로그인 중',
		loginfailure:'로그인 실패',
		loginP:'로그인 비밀번호',
		transactionp:'거래 비밀번호',
		alter:'수정',
		oldP:'이전 비밀번호',
		news:'새롭다',
		confirmP:'비밀번호 확인',
		authcode:'인증번호',
		pleaseInput:'입력해 주세요',
		pleaseInputTwo:'다시 입력해 주세요',
		Confirm:'확인하다',
		Interchange:'서로 바꾸다',
		credited:'수납 계정',
		chamberlain:'수취인',
		Transfer:'반출입 수량',
		all:'모두',
		remaining:'남은 돈',
    },
	index:{
		homepage:'홈페이지',
		store:'상점',
		quantization:'양자화',
		find:'발견하다',
		my:'내꺼',
		more:'점점',
		Cryptocurrency:'암호 통화 이름',
		Latestprice:'최신 가격',
		Updown:'상한가 하락폭',
		Registered:'회원가입',
		Recharge:'채워넣다',
		Mention:'티 머니',
		record:'기록',
		Interchange:'호환 센터',
		community:'저의 지역사회는',
		Agent:'대리 센터',
		BindWallet:'지갑 바인딩',
		Security:'안전센터',
		service:'통신 고객',
		Quantitative:'양화 생태플랫폼',
		assets:'자산',
		partnership:'공동조합원',
		recharges:'일회용 충당',
		equity:'그리고 CR 사원자격을 취득하고 CR 사원의 관련 권익을 향수한다.',
		BuyNow:'지금 구매하기',
		hint:'제시',
		supported:"당신은 이미 대리상의 규칙을 확실하게 이해했습니까?의심의 여지 없는 질문과 이의가 있을 경우,'确定'을 누르면 구매가 성공합니다. 일단 구매하면 어떠한 교환도 지지되지 않습니다"
	},
	notecase:{
		system:'지적 계량화 시스템',
		regulate:'관리',
		spotquantify:'현물의 수량화',
		swapquantify:'협약 수량화',
		follow:'정책 따라가기',
		quantify:'계량적 수익순위표',
		today:'현재',
		week:'이번주',
		month:'지난',
		income:'수익',
		address:'화폐 인수 주소',
		select:'이 주소 편집',
		compile:'편집',
		deletes:'지우다',
		add:'보태다',
		that:'이것',
		name:'성명',
		currency:'화폐의 종류',
		wallet:'지갑 주소',
		your:'저쪽의',
		withdrawal:'공화 듀얼 코드 올려주세요',
		defaults:'묵인하다.',
		uploading:'업로드 중',
		uploadings:'업로드 성공',
		uploadingload:'업로드에 실패했습니다.',
		Chinese:'중국어를 입력할 수 없습니다.'
	},
	store:{
		buy:'구입하다',
		Shopping:'상품권',
		Performance:'업적',
		Product:'제품지역',
		other:'기타',
		spot:'현물의',
		swap:'협약',
		intelligent:'지능',
		robot:'로봇',
		Billing:'데스크 버전',
		profession:'전문',
		Term:'기간 버전',
		Strategy:'전술',
		following:'따르다',
		duration:'시간',
		price:'가격',
		day:'하늘',
		remarks:'비고',
		Billingremarks:'첫 번째 활성화는 반드시 200USDT 가 360일 구입시 길이와 이와 별도로 구입 성공 후 USDT 수수료 잔고가 반드시 10USDT보다 높을 수 있어야 모든 제품 활성화됨',
		
		Enter:'자세한정보',
		XLMT:'스마트버전',
		channel:'초이스해주세요USDT-TRC20통로',
		Sungha:'클릭형 카드',
		Remaining:'잉여',
		pointcard:'카드 를 찍다',
		dot:'점.',
		logon:'시스템 진입',
		beactivated:'활성화 예정',
		version:'판본',
		unpurchased:'미 구입'
	},
	callcenter:{
		unique:'너의 전속',
		WeChat:'위채트',
		customer:'시간 동안 고객서비스 제공',
		employ:'사용',
		Identify:'고객 인식 추가',
		service:'고객센터',
		guide:'지침',
		notice:'공고',
		system:'계통',
		sprog:'새내기',
		amount:'수량',
		Entries:'개',
		duration:'유효 시간',
		buying:'구매 시간',
		payment:'지불 금액',
		completion:'지불 완료',
		inactive:'활성화되지 않음',
		activated:'활성화됨',
		activation:'활성화 시간',
	},
	community:{
		community:'커뮤니티',
		remaining:'남은시간',
		Renew:'요금',
		List:'항렬표',
		search:'검색',
		ranking:'종합 순위',
		type:'유형',
		running:'운행하다',
		trading:'거래 중',
		Stopped:'중지됨',
		population:'인원수',
		accumulative:'누계총계',
		win:'승비율',
		transactions:'거래 필수',
		revenue:'총수익',
		rate:'비율',
		activate:'활성화',
		Feed:'실시간 데이터 업데이트',
		Huobi:'불 머니',
		sustainability:'영원히',
		total:'총괄 하 다',
		money:'금액',
		set:'덫',
		available:'더 많은 데이터가 없습니다',
		loaded:'모든 데이터를 불러왔습니다',
		load:'로드 로드',
	},
	spot:{
		success:'새로 고침 성공',
		Station:'취안추잔',
		instructions:'운영 지침',
		monitoring:'창고 위치 검사',
		configure:'배치',
		Valuation:'금액 표시용 화폐',
		pair:'통화 쌍 추가',
		setup:'한 키 설정 적용하기',
		monitoringtwo:'감시와 통제를 실시하다',
		deals:'매매 홀수',
		profits:'이윤을 완수하다',
		result:'운행 결과',
		Record:'거래 기록',
		Delete:'정책 삭제',
		set:'정책 설정',
		open:'거래를 트다',
		renew:'거래재개',
		stop:'거래정지',
		noopen:'열지 않음',
		status:'상태',
		Under:'모니터링 중',
		Check:'이윤을 남기고 멈추다',
		error:'착오',
		Positioning:'창고 의 위치.',
		capital :'원금이 부족하다',
		singular:'창고 건설 홀수',
		odd:'홑',
		number:'포지션 보유량',
		average:'포지션 평균 가격',
		storehouse:'포지션 평균 가격',
		receipt:'증권 증권',
		profit:'실현이익',
		andloss:'유동 손익',
		proceeds:'수익을 결산하다',
		stoppage:'임시 정지',
		album:'앨범 에 QR 코드 저장 하기',
		site:'코 인 충전 주소',
		copy:'복제 하 다',
		account:'충전 성공 후 거래 하이 ID를 복사하셔서 상자에 입력하고 확인, 시스템인증 후 계정으로 가기',
		hash:'하이 키 입력',
		Cautions:'주의 사항',
		please:'위에 기재한 주소에 USDT-TRC20 외의 어떠한 자산도 충전하지 마십시오. 그렇지 않으면 자산을 찾을 수 없습니다.위에 기재한 주소를 성공적으로 충전하면 거래 하시디 (hahi ID)를 복제하여 온라인상에서 확인 후 장부에 기록해야 합니다.컴퓨터 및 브라우저 보안을 확인하여 정보의 변조나 유출을 방지하십시오',
		wallet:'지갑 주소',
		successtwo:'복사 성공',
		replication:'이 유람기는 복제를 지원하지 않습니다.',
		successfully:'저장에 성공함',
		jurisdiction:'저장에 실패했습니다:변환에 실패했거나 사용할 권한이 없습니다',
		code:'제가 요청했던 두 번째 방법은',
		Invitation:'제 초대장 번호',
		link:'내 초대장 링크',
		poster:'초대장 포스터 생성',
		details:'상금 내역',
		Straight:'사용자를 직접 초청하다',
		Username:'커뮤니티 사용자',
		position:'자리',
		earnings:'금일 이윤',
		Earnings:'수익을 계량화하다',
		Bonus:'금일상여금수익',
		returns:'포상금 총수익',
		 invitation:'내 초대장 상황',
		 Rtime:'등록 시간',
		 rebate:'반 노동자',
		 loadM:'더 불러오기',
		 TradingC:'거래소모',
		 budget:'원금 예산',
			start:'한 번 시작',
			cease:'단 한 번의 정지',
			install:'예산 설정',
			close:'바로가기',
			reset:'초기화 정책',
			amounts:'거래 금액'
	},
	matter:{
		matter:'스마트 거래 유의사항',
		bound:'사용자가 거래소에서 생성한 API를 바인딩할 수 없습니다',
		deal:'스마트 거래 개시 전에 거래소가 원금이 있어야 시스템이 거래를 실행할 수 있다',
		promptly:'在智能交易开启后，如有出现手动介入的情况，系统将立即 停止交易'
	}
}