module.exports = {
	language: {
		name: '中文'
	},
	user: {
		login: '登录',
		register: '注册',
		loginUsername: '请输入手机号或邮箱',
		enterPassword: '请输入密码',
		remenberP: '记住密码',
		forgetP: '忘记密码',
		readAgree: '我已阅读并完全同意接受',
		userAgreement: '用户协议',
		riskwarning: '风险提示书',
		download: '下载',
		yourname: '请输入您的用户昵称',
		yourpassword: '请输入你的登录密码',
		yourpasswordtwo: '请再次输入你的登录密码',
		transactionpassword: '请输入你的交易密码',
		transactionpasswordtwo: '请再次输入你的交易密码',
		Invitationcode: '请输入您的邀请码',
		verification: '请输入验证码',
		getcode: '获取验证码',
		gain: '获取',
		Pleasecomplete: '请填写完整',
		donmatch: '两次密码不一致',
		transactionmatch: '两次交易密码不一致',
		readAgreement: '请阅读用户协议',
		Islanding: '正在登陆',
		loginfailure: '登陆失败',
		loginP:'登录密码',
		transactionp:'交易密码',
		alter:'修改',
		oldP:'旧密码',
		news:'新',
		confirmP:'确认密码',
		authcode:'验证码',
		pleaseInput:'请输入',
		pleaseInputTwo:'请再次输入',
		Confirm:'确认',
		Interchange:'互转',
		credited:'收款账户',
		chamberlain:'收款人',
		Transfer:'转出数量',
		all:'全部',
		remaining:'余额',
	},
	index: {
		homepage: '首页',
		store: '商城',
		quantization: '量化',
		find: '发现',
		my: '我的',
		more: '更多',
		Cryptocurrency: '加密货币名称',
		Latestprice: '最新价',
		Updown: '涨跌幅',
		Registered: '注册会员',
		Recharge: '充值',
		Mention: '提币',
		record: '记录',
		Interchange: '互转中心',
		community: '我的社区',
		Agent: '代理中心',
		BindWallet: '绑定钱包',
		Security: '安全中心',
		service: '联系客服',
		Quantitative: '量化生态平台',
		assets: '资产',
		partnership:'合伙人',
		recharges:'一次性充值',
		equity:'并获得CR合伙人资格,享受CR合伙人相关权益',
		BuyNow:'立即购买',
		hint:'提示',
		supported:"您是否已经了解清楚代理商规则。如无疑问和异议，点击'确定'即购买成功，一经购买，不支持任何退换"
	},
	notecase: {
		system: '智慧量化系统',
		regulate: '管理',
		spotquantify: '现货量化',
		swapquantify: '合约量化',
		follow: '策略跟随',
		quantify: '量化收益排行榜',
		today: '今日',
		week: '本周',
		month: '本月',
		income: '收益',
		address:'提币地址',
		select:'选择该地址',
		compile:'编辑',
		deletes:'删除',
		add:'添加',
		that:'这个',
		name:'姓名',
		currency:'币种',
		wallet:'钱包地址',
		your:'您的',
		withdrawal:'请上传提币二维码',
		defaults:'默认',
		uploading:'正在上传',
		uploadings:'上传成功',
		uploadingload:'上传失败',
		Chinese:'不能输入中文'
	},
	store: {
		buy: '购买',
		Shopping: '购物券',
		Performance: '业绩',
		Product: '产品区',
		other: '其他',
		spot: '现货',
		swap: '合约',
		intelligent: '智能',
		robot: '机器人',
		Billing: '计费版',
		profession: '专业',
		Term: '期限版',
		Strategy: '策略',
		following: '跟随',
		duration: '时长',
		price: '价格',
		day: '天',
		remarks: '备注',
		Billingremarks: '首次激活必须200USDT购买360天时长,另外购买成功后USDT手续费余额不低于10USDT才能激活所有产品开启交易',
		Enter: '进入详情',
		XLMT:'智能版',
		channel:'请选择USDT-TRC20通道',
		Sungha:'点卡版',
		Remaining:'剩余',
		pointcard:'点卡',
		dot:'点',
		logon:'进入系统',
		beactivated:'待激活',
		version:'版本',
		unpurchased:'未购买'
	},
	callcenter: {
		unique: '您的专属',
		WeChat: '微信',
		customer: '小时为您提供客服服务',
		employ: '使用',
		Identify: '识别添加客服',
		service:'客服',
		guide:'指南',
		notice:'公告',
		system:'系统',
		sprog:'新手',
		amount:'数量',
		Entries:'个',
		duration:'有效时长',
		buying:'购买时间',
		payment:'支付金额',
		completion:'支付完成',
		inactive:'未激活',
		activated:'已激活',
		activation:'激活时间',
	},
	community:{
		community:'社区',
		remaining:'剩余时长',
		Renew:'续费',
		List:'列表',
		search:'搜索',
		ranking:'综合排名',
		type:'类型',
		running:'运行',
		trading:'交易中',
		Stopped:'已停止',
		population:'跟随人数',
		accumulative:'累计总',
		win:'胜率',
		transactions:'交易笔数',
		revenue:'总收益',
		rate:'率',
		activate:'激活',
		Feed:'数据实时更新',
		Huobi:'火币',
		sustainability:'永续',
		total:'总',
		money:'金额',
		set:'套',
		available:'暂无更多数据',
		loaded:'已加载完所有数据',
		load:'下拉加载',
	},
	spot:{
		success:'刷新成功',
		Station:'全球站',
		instructions:'操作指南',
		monitoring:'仓位监测',
		configure:'配置',
		Valuation:'计价币',
		pair:'添加货币对',
		setup:'一键设置应用',
		monitoringtwo:'实时监控',
		deals:'成交单数',
		profits:'完成利润',
		result:'运行结果',
		Record:'成交记录',
		Delete:'删除策略',
		set:'设置策略',
		open:'开启交易',
		renew:'恢复交易',
		stop:'停止交易',
		noopen:'未开启',
		status:'状态',
		Under:'正在监控中',
		Check:'止盈后停止',
		error:'错误',
		Positioning:'仓位',
		capital :'本金不足',
		singular:'建仓单数',
		odd:'单',
		number:'持仓数量',
		average:'持仓均价',
		storehouse:'尾仓均价',
		receipt:'平仓单数',
		profit:'实现利润',
		andloss:'浮动盈亏',
		proceeds:'结算收益',
		stoppage:'临时停止',
		album:'保存二维码至相册',
		site:'充币地址',
		copy:'复制',
		account:'充值成功后请复制交易哈希ID在输入框后点击确认，系统认证后即到账',
		hash:'输入哈希值',
		Cautions:'注意事项',
		please:'请勿向上述地址充值任何非USDT-TRC20资产，否则资产将不可找回。您充值至上述地址成功后，需要复制交易哈希ID，网络确认后到账。请务必确认电脑及浏览器安全，防止信息被篡改或泄露',
		wallet:'钱包地址',
		successtwo:'复制成功',
		replication:'该浏览器不支持自动复制',
		successfully:'保存成功',
		jurisdiction:'保存失败：转码失败或没有相册使用权限',
		code:'我的邀请二维码',
		Invitation:'我的邀请码',
		link:'我的邀请链接',
		poster:'生成邀请海报',
		details:'奖金明细',
		Straight:'直邀用户',
		Username:'社区用户',
		position:'位',
		earnings:'今日盈利',
		Earnings:'量化总盈利',
		Bonus:'今日奖金收益',
		returns:'奖金总收益',
		invitation:'我的邀请详情',
		Rtime:'注册时间',
		rebate:'返佣',
		loadM:'加载更多',
		TradingC:'交易消耗',
		budget:'本金预算',
		start:'一键启动',
		cease:'一键停止',
		install:'预算设置',
		close:'一键平仓',
		reset:'重置策略',
		amounts:'交易金额'
	},
	matter:{
		matter:'智能交易注意事项',
		bound:'用户在交易所内生成的API不可绑定IP',
		deal:'在智能交易开启前，交易所中必须先有本金，系统才能执行交易',
		promptly:'在智能交易开启后，如有出现手动介入的情况，系统将立即 停止交易'
	}
}
